pub const TCP_PORT: &str = "TCP_PORT";
pub const LOG_DIRECTORY: &str = "LOG_DIRECTORY";
pub const DOWNLOAD_DIRECTORY: &str = "DOWNLOAD_DIRECTORY";
pub const PIPELINING_SIZE: &str = "PIPELINING_SIZE";
pub const READ_WRITE_SECONDS_TIMEOUT: &str = "READ_WRITE_SECONDS_TIMEOUT";
pub const MAX_PEERS_PER_TORRENT: &str = "MAX_PEERS_PER_TORRENT";
pub const MAX_LOG_FILE_KB_SIZE: &str = "MAX_LOG_FILE_KB_SIZE";

pub const MIN_SETTINGS: i8 = 7;
